# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190322_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
