# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-23 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20190322_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Editor',
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
